version: '3.8'

services:
  api:
    build:
      context: ./DeviceMonitoringAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - monitoring-net

  spa:
    build:
      context: ./DeviceMonitoringSPA
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge